name: Label Bot bump PRs

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  label-pr:
    if: github.event.pull_request.user.login == 'Picardas-Bot'
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: Homebrew/actions/label-pull-requests@main
        with:
          token: ${{ secrets.REPO_WORKFLOW_TOKEN }}
          def: |
            [
              {
                "label": "bump-pr",
                "pr_body_content": "Created with `brew bump-cask-pr`"
              }
            ]
