name: Automerge bump PRs

on:
  pull_request:
    types: [labeled]
    branches: [main]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'bump-pr')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main
        with:
          username: Picardas-Bot

      - name: Set up commit signing
        uses: Homebrew/actions/setup-commit-signing@main
        with:
          signing_key: ${{ secrets.BOT_SSH_SIGNING_KEY }}

      - name: Wait for Status Checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.REPO_WORKFLOW_TOKEN }}

      - name: Merge PR
        run: gh pr merge ${{ github.event.pull_request.number }} --merge
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_WORKFLOW_TOKEN }}
